---
# tasks file for jenkins
- name: add jenkins key
  apt_key:
    state: present
    url: "{{ jenkins_key_rpmU }}"

- name: "Set Jenkins apt repository"
  apt_repository:
      repo: "{{ jenkins_repo_urlU }}"
      state: present
      update_cache: true

- name: "Install Java and Jenkins"
  apt:
      name: "{{ item.value.name }}" 
      state: present
  loop:
      "{{ lookup('dict',softwaresU) }}"

- name: "Starting jenkins"
  service:
      name: "jenkins"
      state: started
      enabled: yes
